### ISSUE TITLE
dichotomic_search test suite

### ISSUE THREAD

**Issue by oldmammuth** [EricAlcaide/Rosetta_Stone#10]
The dichotomic_search README.md presents explicitly the algo as working on an ordered array; in fact, both python and JS implementations take advantage of the orderly array using a recursion over a `if X < Y`.
A problem arises with the two last lines of the test suite, namely:
```
["I","am","a","test","for","Roseta","Stone","algo","lib"] "HELLO" >> null

["I","am","a","test","for","Roseta","Stone","algo","lib"] "Stone" >> "Stone"
```
These two arrays are not ordered; thus the implementation of the first in most languages will end up with a `null` as supposed, since the list is not ordered; the second will end up with a `null` also, since it is not ordered. However, even a `null` cannot be accepted as a good test-case, since the algorithm is supposed to break and be in a uncertain state when used over unordered arrays.

**Comment by EricAlcaide** [comment]
Yes exactly, planning to remove those lines in the next commit.

**Comment by EricAlcaide** [comment]
Already removed. This issue can be closed.
