### ISSUE TITLE
Dichotomic search one-liner

### ISSUE THREAD

**Issue by EricAlcaide** [EricAlcaide/Rosetta_Stone#2]
The one-liner in the return statement is ugly and makes the code difficult to understand. Fewer lines don't always mean better code. Is there a way to replace it? @AleixSanfe

**Comment by AleixSanfe** [comment]
I can think of three posible options:

- A proper indentation of the return statement, which would make it more readable while being just one line of code:
```
return 	array.length > 1 ? 
    array[med] > v ? 
        dichotomic_search(array.splice(0,med),v) : 
        dichotomic_search(array.splice(med,array.length),v) : 

    array[0] == v ? 
        v : 
        null;
```
- The use of a if-else structure with both the default if and the conditional operator:
```
if (array.length > 1) 
    return array[med] > v ?
        dichotomic_search(array.splice(0,med),v)  :
        dichotomic_search(array.splice(med,array.length),v)  ;
else
    return array[0] == v ?
        v :
        null ;
```
- The exclusive use of the default if-else, having a nested structure:
```
if (array.length > 1){
    if (array[med] > v) return dichotomic_search(array.splice(0,med),v) ;
    else dichotomic_search(array.splice(med,array.length),v) ;
}else {
    if (array[0] == 0) return v ;
    else return null
}
```

Any of them are equally  valid, it's jsut a matter of style.

**Comment by EricAlcaide** [comment]
Hmm,  the first or the second one I think... but I would put `v : null;`  on the same line... what do you think?

**Comment by EricAlcaide** [comment]
This issue can be closed because a new version of dicho js has been added to the repo
