### ISSUE TITLE
Add Hacktoberfest label to get more contributors 

### ISSUE THREAD

**Issue by robeerob** [EricAlcaide/Rosetta_Stone#3]
I really love this repo! Thanks a lot for creating this.

Would be great to see even more algorithms and code added, and I would suggest to add an issue with Hacktoberfest label asking for PRs.

**Comment by EricAlcaide** [comment]
Done! Also assigned Hacktoberfest label to this issue!

**Comment by EricAlcaide** [comment]
We'll leave it open for now in order to encourage people to contribute...

**Comment by robeerob** [comment]
@EricAlcaide Great, thanks. Good luck :+1:

**Comment by EricAlcaide** [comment]
Great Idea!

**Comment by EricAlcaide** [comment]
Already done. This issue can be closed.
