### ISSUE TITLE
http://rosettacode.org

### ISSUE THREAD

**Issue by barmanoo** [EricAlcaide/Rosetta_Stone#7]
A very similar project already exists since many years at:
http://rosettacode.org/wiki/Rosetta_Code

Cheers

**Comment by EricAlcaide** [comment]
Yes, it's very similar in content, but the intention is different. the intention behind rosettacode.org is to see the differences between languages, but the algorithms implemented there are basically mathematical algos. 
This project is intended to be a starting point for anyone trying to learn a new language. I think that the majority of the people won't try to draw a fractal tree while learning a new language. The majority of the code snippets in rosettacode.org are scientific-based while this project is intended to be a set of practical real examples.
